name: McCity Help
main: RiseOfDeath.Help.Help
author: RiseOfDeath
version: 0.3.0
database: false
softdepend: [Permissions]
website: minecraft-mccity.ru
commands:
   help:
      description: use for getting help
      usage: |
         /help - for help
         /help [topic_name] - print this topic (they are green)
         /help [subfolder_name] - open subfolder (they are yellow)
         /help back - open previous folder (close current topic, and go to his folder)
         /help find [topic_name] - try find (and show) topic [topic_name]
         /help find [tag_name] - find and show list of all topics, which have this tag. 
         Just type after /help [any_topic_from_the_list_of_founded_topics]
   adminhelp:
      description: use for setting help
      usage: |
         /adminhelp new [title]- create new topic
         /adminhelp addstring [topic's string]  - add new string into this topic
         /adminhelp permission [permission] - set permission (default mccityhelp.user)
         /adminhelp save [path] - save it at /main/%path%/%title%.yml
         /adminhelp save - save it at /main/%title%.yml
         /adminhelp color - show you Chat Colors